### ISSUE TITLE
Syntax error in hokalman

### ISSUE THREAD

**Issue by jasonnicholson** [DanielMartensson/Mataveid#14]
https://github.com/DanielMartensson/Mataveid/blob/7b4630798bb019d8b0085f0f36d7e6cc697c839b/old/source/hokalman.m#L75-L76

Replace endfunction with end.

Should there be a multiply sign between hankel(g) and (1:length(g)/2,1+k:length(g)/2+k)?

**Comment by DanielMartensson** [comment]
Ho-Kalman is the absolute first algorithm that is used for state space identification. It has been replaced with eradc.m. I'm not using ho-kalman algorithm.

I belive that ho-kalman was invented in 1965.

**Comment by jasonnicholson** [comment]
Can we delete it but leave it in the git history since it's not used?

**Comment by DanielMartensson** [comment]
Yes. But I would like to have a folder where old stuffs belongs. Just in case.
