### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by ColleyLi** [DanielMartensson/Mataveid#2]
Thank you for your open source, but there are some  problems in running the example code:ss function
help ss
ss - Create state-space model, convert to state-space model

    This MATLAB function creates a state-space model object representing the
    continuous-time state-space model
    sys = ss(A,B,C,D)
another problem is missing raw data

**Comment by DanielMartensson** [comment]
> Thank you for your open source, but there are some problems in running the example code:ss function
> help ss
> ss - Create state-space model, convert to state-space model
> 
> ```
> This MATLAB function creates a state-space model object representing the
> continuous-time state-space model
> sys = ss(A,B,C,D)
> ```
> 
> another problem is missing raw data

Hmm.. Why did I not get a notification from GitHub?

Anyway! Hi!

you need to write:

```
delayValue = 0; % or 1 what ever.
sys = sys(delayValue, A, B, C, D)
```

Notice if you only write
```
delayValue = 0; % or 1 what ever.
sys = sys(delayValue, A, B)
```
C and D will be automatically defined for you :)

To get a discrete delay, please use c2dt function. Delays can only be discrete.
